In [1]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pandas as pd

In [2]:
df = pd.read_csv('./ETL-EDA/ETL_ETIQUETAS.csv')
nombres = pd.read_csv('./ETL-EDA/NombresJuegos.csv')
# Selecciona las características relevantes para el modelo
features = df.columns.values.tolist()
features.remove("IdItem")

In [6]:
# Preprocesamiento y normalización de datos
df_features = df[features]
scaler = MinMaxScaler()
df_normalized = scaler.fit_transform(df_features)
# Cálculo de la similitud de coseno
similarities = cosine_similarity(df_normalized)

In [7]:
# Función para obtener los ítems más similares dado un ítem de referencia
def obtener_similares(id_item_referencia, n=5):
    index_referencia = df[df['IdItem'] == id_item_referencia].index[0]
    similar_indices = similarities[index_referencia].argsort()[::-1][:n+1]
    similar_items = df.iloc[similar_indices]
    return similar_items

In [41]:
id_item_referencia = 48000  # Id del ítem de referencia
items_similares = obtener_similares(id_item_referencia)
print(items_similares["IdItem"])

11968     48000
14567     63710
23451    270510
29929    212030
3413      22230
14792    263740
Name: IdItem, dtype: int64

In [42]:
dfResultado = pd.merge(items_similares, nombres, on='IdItem')
dfResultado.iloc[:,[0,59]]

   IdItem                               Titulo
0   48000                                LIMBO
1   63710                      BIT.TRIP RUNNER
2  270510                                EPOCH
3  212030  Kung Fu Strike - The Warrior's Rise
4   22230                         Rock of Ages
5  263740            FootLOL: Epic Fail League

In [43]:
dfResultado

,IdItem,Tiempo_Jugado_Promedio,Recomendado,Precio,Etiqueta_2D,Etiqueta_Action,Etiqueta_Adventure,Etiqueta_Anime,Etiqueta_Arcade,Etiqueta_Atmospheric,...,Etiqueta_Space,Etiqueta_Sports,Etiqueta_Story Rich,Etiqueta_Strategy,Etiqueta_Survival,Etiqueta_Tactical,Etiqueta_Third Person,Etiqueta_Turn-Based,Etiqueta_Zombies,Titulo
0,48000,154,1,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,LIMBO
1,63710,154,1,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,BIT.TRIP RUNNER
2,270510,155,1,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,EPOCH
3,212030,156,1,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Kung Fu Strike - The Warrior's Rise
4,22230,156,1,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Rock of Ages
5,263740,152,1,9,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,FootLOL: Epic Fail League